SELECT
avg(IfNull(added_points_qnt, 0)) as metric
FROM digital_product_analytics.app_metric_events
WHERE toDate(event_datetime) = toDate(date_sub(now(), 1)) AND event_name IN ('system_order_create_success')
ORDER BY metric
CREATE MATERIALIZED VIEW digital_product_analytics.app_metric_consumer
ON CLUSTER '{cluster}'
TO digital_product_analytics.app_metric_events
(
    event_name String,
    event_datetime DateTime,
    event_timestamp UInt32,
    event_json String,
    restaurant_id Int64,
    kiosk_device_id String,
    kiosk_device_name String,
    kiosk_session_id String,
    order_id String,
    session_length Int64,
    language String,
    screen_name String,
    object_type String,
    source_code String,
    authenticated_flg String,
    category_id String,
    product_qnt Int64,
    order_value Int64,
    used_points_qnt Int64,
    added_points_qnt Int64,
    coupon_code String,
    banner_file_name String,
    banner_file_url String,
    link String,
    error_description String,
    error_code String,
    category_name String,
    product_name String,
    product_id String,
    price UInt32,
    price_point String,
    time_spent UInt32,
    modificator_added_flg String,
    modificator_removed_flg String,
    ingredient_added_flg String,
    ingredient_removed_flg String,
    loyalty_product_flg String,
    modificator_name String,
    modificator_id String,
    ingredient_name String,
    ingredient_id String,
    recommendations String,
    cat_prod_ids Array(String),
    ab_test String,
    provider_type String,
    event_receive_datetime DateTime,
    event_receive_timestamp UInt32,
    application_id UInt32,
    appmetrica_device_id String,
    profile_id String,
    appmetrica_session_id UInt64,
    appmetrica_session_type String,
    app_version_name String,
    app_build_number String,
    app_package_name String,
    country_iso_code String,
    city String,
    device_ipv6 String,
    device_type String,
    device_model String,
    original_device_model String,
    device_manufacturer String,
    os_name String,
    os_version String,
    device_locale String,
    connection_type String,
    mcc String,
    mnc String,
    operator_name String,
    installation_id String,
    android_id String,
    google_aid String,
    ios_ifa String,
    ios_ifv String,
    windows_aid String,
    stream_window_timestamp UInt32,
    loaded_at_from_api Nullable (DateTime)
) AS
SELECT
    event_name,
    event_datetime,
    event_timestamp,
    event_json,
    JSONExtractInt (event_json, 'restaurant_id') AS restaurant_id,
    JSONExtractString (event_json, 'device_id') AS kiosk_device_id,
    JSONExtractString (event_json, 'device_name') AS kiosk_device_name,
    JSONExtractString (event_json, 'session_id') AS kiosk_session_id,
    JSONExtractString (event_json, 'order_id') AS order_id,
    JSONExtractInt (event_json, 'session_length') AS session_length,
    JSONExtractString (event_json, 'language') AS language,
    JSONExtractString (event_json, 'screen_name') AS screen_name,
    JSONExtractString (event_json, 'object_type') AS object_type,
    JSONExtractString (event_json, 'source_code') AS source_code,
    JSONExtractString (event_json, 'authenticated_flg') AS authenticated_flg,
    JSONExtractString (event_json, 'category_id') AS category_id,
    JSONExtractInt (event_json, 'product_qnt') AS product_qnt,
    JSONExtractInt (event_json, 'order_value') AS order_value,
    JSONExtractInt (event_json, 'used_points_qnt') AS used_points_qnt,
    JSONExtractInt (event_json, 'added_points_qnt') AS added_points_qnt,
    JSONExtractString (event_json, 'coupon_code') AS coupon_code,
    JSONExtractString (event_json, 'banner_file_name') AS banner_file_name,
    JSONExtractString (event_json, 'banner_file_url') AS banner_file_url,
    JSONExtractString (event_json, 'link') AS link,
    JSONExtractString (event_json, 'error_description') AS error_description,
    JSONExtractString (event_json, 'error_code') AS error_code,
    JSONExtractString (event_json, 'category_name') AS category_name,
    JSONExtractString (event_json, 'product_name') AS product_name,
    JSONExtractString (event_json, 'product_id') AS product_id,
    JSONExtractInt (event_json, 'price') AS price,
    JSONExtractString (event_json, 'price_point') AS price_point,
    JSONExtractInt (event_json, 'time_spent') AS time_spent,
    JSONExtractString (event_json, 'modificator_added_flg') AS modificator_added_flg,
    JSONExtractString (event_json, 'modificator_removed_flg') AS modificator_removed_flg,
    JSONExtractString (event_json, 'ingredient_added_flg') AS ingredient_added_flg,
    JSONExtractString (event_json, 'ingredient_removed_flg') AS ingredient_removed_flg,
    JSONExtractString (event_json, 'loyalty_product_flg') AS loyalty_product_flg,
    JSONExtractString (event_json, 'modificator_name') AS modificator_name,
    JSONExtractString (event_json, 'modificator_id') AS modificator_id,
    JSONExtractString (event_json, 'ingredient_name') AS ingredient_name,
    JSONExtractString (event_json, 'ingredient_id') AS ingredient_id,
    JSONExtractString (event_json, 'recommendations') AS recommendations,
    arrayConcat(
                arrayDistinct(arrayMap(x -> JSONExtractString(JSONExtractRaw(x, toString(indexOf(JSONExtractArrayRaw(recommendations), x) - 1)), 'productId'), JSONExtractArrayRaw(recommendations)))
           ) as cat_prod_ids,
    JSONExtractString (event_json, 'ab_test_name') AS ab_test_name,
    JSONExtractString (event_json, 'ab_test_variant_name') AS ab_test_variant_name,
    event_receive_datetime,
    event_receive_timestamp,
    application_id,
    appmetrica_device_id,
    profile_id,
    session_id AS appmetrica_session_id,
    session_type AS appmetrica_session_type,
   app_version_name,
    app_build_number,
    app_package_name,
    country_iso_code,
    city,
    device_ipv6,
    device_type,
    device_model,
    original_device_model,
    device_manufacturer,
    os_name,
    os_version,
    device_locale,
    connection_type,
    mcc,
    mnc,
    operator_name,
    installation_id,
    android_id,
    google_aid,
    ios_ifa,
    ios_ifv,
    windows_aid,
    stream_window_timestamp,
    parseDateTimeBestEffortOrNull (loaded_at_from_api) AS loaded_at_from_api
FROM digital_product_analytics.app_metric_raw_events_s3queue
