configurations_ab:







  - metric_id: 1







    slice_type: "date, restaurant_id"







    aggregator: "order_value"







    aggregation_type: "mean"







    parameter: "none"







    test: "ttest"







    split_method: "from_csv"







    method: "bootstrap"







    bootstrap_method: "normal"







    bootstrap_cycles: 100







    lower_bound: 0







    upper_bound: 1







    MDE: 6







    alpha: 0.05







    beta: 0.2















common_config_ab:







  exp_id: 1







  dbname: "db"







  user: "codespace"







  host: "localhost"







  project: "kfc-kiosk-3"







  location: "US"







  query_id: "bquxjob_159f1b6a_18cedf71333"







  kiosk_path: C:\ROSTICS-LAB\project\static\test_data\data_1_testing.csv







  groups_path: C:\ROSTICS-LAB\project\static\test_data\test_stratification_groups140_2.csv







  name: "ab_test_3"







  start_date: "2024-04-09"







  data_collect_start_date: "2024-04-01"







  data_collect_end_date: "2024-04-18"